version: '3.5'

services:
  postgres:
    container_name: pg_my_timer_prod
    image: postgres:14
    environment:
      # POSTGRES_DB: "my_timer"
      # POSTGRES_USER: "my_timer_user"
      # POSTGRES_PASSWORD: "pgusermytimer"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - /home/dav/WorkMyProject/my_timer_bd/Init Database:/docker-entrypoint-initdb.d
      - /home/dav/WorkMyProject/my_timer_bd/:/var/lib/postgresql/data
    # ports:
    #   - "5445:5432"
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U my_timer_user -d my_timer"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    env_file:
          - ./my_timer_project/my_timer/.env.prod
    networks:
      - my_timer_work

  mytimer:
    image: mytimer_prod
    build:
      context: ./my_timer_project
      dockerfile: Dockerfile
    command: gunicorn my_timer.wsgi:application --bind 0.0.0.0:8000
    # ports:
    #   - 8100:8100
    expose:
      - 8000
    networks:
      - my_timer_work
    depends_on:
          - postgres
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 0.5G
    env_file:
          - ./my_timer_project/my_timer/.env.prod


networks:
  my_timer_work:
    driver: bridge